import * as THREE from 'three'
import { GreenTerrain } from '../../domain/physics/GreenTerrain'
import type { WaterHazard } from '../../domain/physics/GreenTerrain'

/** Renders deterministic organic water hazards generated by GreenTerrain. */
export class WaterHazardRenderer {
  private readonly terrain: GreenTerrain
  private readonly root = new THREE.Group()
  private readonly material = new THREE.MeshPhongMaterial({
    color: 0x2f6f9f,
    transparent: true,
    opacity: 0.66,
    side: THREE.DoubleSide,
    shininess: 60,
    depthWrite: false,
    polygonOffset: true,
    polygonOffsetFactor: -1,
    polygonOffsetUnits: -1,
  })
  private readonly meshes: THREE.Mesh[] = []

  constructor(terrain: GreenTerrain) {
    this.terrain = terrain
    this.root.name = 'water-hazards'
    this.updateFromTerrain()
  }

  getObject3D(): THREE.Group {
    return this.root
  }

  updateFromTerrain(): void {
    this.clearMeshes()

    for (const hazard of this.terrain.getWaterHazards()) {
      const mesh = this.createWaterMesh(hazard)
      this.meshes.push(mesh)
      this.root.add(mesh)
    }
  }

  dispose(): void {
    this.clearMeshes()
    this.material.dispose()
  }

  private createWaterMesh(hazard: WaterHazard): THREE.Mesh {
    const geometry = new THREE.BufferGeometry()
    const vertices: number[] = [0, 0, 0]
    const indices: number[] = []

    for (const point of hazard.outline) {
      vertices.push(point.x, 0, point.z)
    }

    for (let i = 1; i <= hazard.outline.length; i++) {
      const next = i === hazard.outline.length ? 1 : i + 1
      indices.push(0, i, next)
    }

    geometry.setAttribute('position', new THREE.BufferAttribute(new Float32Array(vertices), 3))
    geometry.setIndex(indices)
    geometry.computeVertexNormals()

    const mesh = new THREE.Mesh(geometry, this.material)
    mesh.name = 'water-hazard'
    mesh.position.set(hazard.centerX, this.terrain.getWaterLevel(hazard), hazard.centerZ)
    mesh.rotation.set(0, hazard.rotation, 0)
    mesh.receiveShadow = false
    mesh.castShadow = false
    return mesh
  }

  private clearMeshes(): void {
    for (const mesh of this.meshes) {
      mesh.geometry.dispose()
      this.root.remove(mesh)
    }
    this.meshes.length = 0
  }
}
